import onnx
import numpy as np
DATA_SIZE_DTYPE = {
        onnx.TensorProto.FLOAT:32,
        onnx.TensorProto.UINT8:8,
        onnx.TensorProto.INT8:8,
        onnx.TensorProto.UINT16:16,
        onnx.TensorProto.INT16:16,
        onnx.TensorProto.INT32:32,
        onnx.TensorProto.INT64:64,
        onnx.TensorProto.STRING: 4,
        onnx.TensorProto.BOOL:1,
        onnx.TensorProto.FLOAT16:16,
        onnx.TensorProto.DOUBLE:64,
        onnx.TensorProto.UINT32:32,
        onnx.TensorProto.UINT64:64,
        onnx.TensorProto.COMPLEX64:64,
        onnx.TensorProto.COMPLEX128:128,
        onnx.TensorProto.BFLOAT16:16,
    }

ONNX_DTYPE = {
        1: onnx.TensorProto.FLOAT,
        2: onnx.TensorProto.UINT8,
        3: onnx.TensorProto.INT8,
        4: onnx.TensorProto.UINT16,
        5: onnx.TensorProto.INT16,
        6: onnx.TensorProto.INT32,
        7: onnx.TensorProto.INT64,
        8: onnx.TensorProto.STRING,
        9: onnx.TensorProto.BOOL,
        10: onnx.TensorProto.FLOAT16,
        11: onnx.TensorProto.DOUBLE,
        12: onnx.TensorProto.UINT32,
        13: onnx.TensorProto.UINT64,
        14: onnx.TensorProto.COMPLEX64,
        15: onnx.TensorProto.COMPLEX128,
        16: onnx.TensorProto.BFLOAT16,
    }
ONNX_ATTRIBUTE_TYPE ={
    onnx.AttributeProto.AttributeType.UNDEFINED: 0,
    onnx.AttributeProto.AttributeType.FLOAT: 1,
    onnx.AttributeProto.AttributeType.INT: 2,
    onnx.AttributeProto.AttributeType.STRING: 3,
    onnx.AttributeProto.AttributeType.TENSOR: 4,
    onnx.AttributeProto.AttributeType.GRAPH: 5,
    onnx.AttributeProto.AttributeType.SPARSE_TENSOR :11,
    onnx.AttributeProto.AttributeType.TYPE_PROTO :13,
    onnx.AttributeProto.AttributeType.FLOATS: 6,
    onnx.AttributeProto.AttributeType.INTS: 7,
    onnx.AttributeProto.AttributeType.STRINGS: 8,
    onnx.AttributeProto.AttributeType.TENSORS: 9,
    onnx.AttributeProto.AttributeType.GRAPHS :10,
    onnx.AttributeProto.AttributeType.SPARSE_TENSORS :12,
    onnx.AttributeProto.AttributeType.TYPE_PROTOS :14,
    }
NUMPY_DTYPE = {
            1: np.float32,
            2: np.uint8,
            3: np.int8,
            4: np.uint16,
            5: np.int16,
            6: np.int32,
            7: np.int64,
            8: str,
            9: np.bool_,
            10: np.float16,
            11: np.double,
            12: np.uint32,
            13: np.uint64,
            14: np.complex64,
            15: np.complex128,
            16: np.float16,
        }